### ISSUE TITLE
Link to Chrome Web Store in readme

### ISSUE THREAD

**Issue by NomarCub** [BenignPigeon/Extension-Grabber#3]
This extension is up on the Chrome WebStore, it has a link to here, but there's no link from this repo to there.
For all I know the author could be faked in either direction, the link to the store should be here, for findability and trust.

**Comment by BenignPigeon** [comment]
Thanks for this suggestion, I will provide links to the github on the extension listing and links to the chrome store on the github repo.  Please let me know if there's anything else that would make this clearer.

**Comment by NomarCub** [comment]
Thanks!
If I may point out, the current readme is pretty wordy and not really to the point. The main gist could be expressed in like 2 bullet points.

**Comment by BenignPigeon** [comment]
yeah, definitely! 
short and snappy is way better idk why I wrote that wall of text.
please keep giving me feedback since I'm rather new to this and I want to make any improvements that I can.
(:
